# Map to handle the Microphone Permission Exception for Starmus
map $request_uri $spx_permissions {
    default "accelerometer=(), autoplay=(self), camera=(self), clipboard-read=(self), clipboard-write=(self), ge>

    # Enable microphone specifically for your audio submission page
    "~^/star-submit-audio/?" "accelerometer=(), autoplay=(self), camera=(self), clipboard-read=(self), clipboard>
}
