map $ssl_server_name $cert_file {
    default                        /etc/ssl/certs/system-core.crt;

    sparxstar.com                  /etc/ssl/certs/sparxstar.com.crt;
    *.sparxstar.com                /etc/ssl/certs/sparxstar.com.crt;

    aiwestafrica.com               /etc/ssl/certs/aiwestafrica.com.crt;
    *.aiwestafrica.com             /etc/ssl/certs/aiwestafrica.com.crt;

    cellularvibrations.com         /etc/ssl/certs/cellularvibrations.com.crt;
    *.cellularvibrations.com       /etc/ssl/certs/cellularvibrations.com.crt;
}

map $ssl_server_name $key_file {
    default                        /etc/ssl/private/system-core.key;

    sparxstar.com                  /etc/ssl/private/sparxstar.com.key;
    *.sparxstar.com                /etc/ssl/private/sparxstar.com.key;

    aiwestafrica.com               /etc/ssl/private/aiwestafrica.com.key;
    *.aiwestafrica.com             /etc/ssl/private/aiwestafrica.com.key;

    cellularvibrations.com         /etc/ssl/private/cellularvibrations.com.key;
    *.cellularvibrations.com       /etc/ssl/private/cellularvibrations.com.key;
}
