proxy_set_header X-SPARXSTAR-User       $spx_pass_sparxstar_user;
proxy_set_header X-SPARXSTAR-Session    $spx_pass_sparxstar_session;
proxy_set_header X-SPARXSTAR-Roles      $spx_pass_sparxstar_roles;
proxy_set_header X-SPARXSTAR-Issued     $spx_pass_sparxstar_issued;
proxy_set_header X-SPARXSTAR-Expires    $spx_pass_sparxstar_expires;
proxy_set_header X-SPARXSTAR-Site       $spx_pass_sparxstar_site;
proxy_set_header X-SPARXSTAR-AuthLevel  $spx_pass_sparxstar_authlevel;
