# -------------------------------------------------
# BLOCK SENSITIVE FILES
# -------------------------------------------------

location ~* /\.(env|git|svn|hg) {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* \.(conf|ini|log|bak|sql|sh|dist|example|sample)$ {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* \.(yml|yaml|toml|lock)$ {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* /(composer\.(json|lock)|package\.json|package-lock\.json|yarn\.lock)$ {
    deny all;
    access_log off;
    log_not_found off;
}

location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
}
