proxy_set_header X-SPARXSTAR-User       $http_x_sparxstar_user;
proxy_set_header X-SPARXSTAR-Session    $http_x_sparxstar_session;
proxy_set_header X-SPARXSTAR-Roles      $http_x_sparxstar_roles;
proxy_set_header X-SPARXSTAR-Issued     $http_x_sparxstar_issued;
proxy_set_header X-SPARXSTAR-Expires    $http_x_sparxstar_expires;
proxy_set_header X-SPARXSTAR-Site       $http_x_sparxstar_site;
proxy_set_header X-SPARXSTAR-AuthLevel  $http_x_sparxstar_authlevel;
